name: scraper

on:
  pull_request

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
