name: scraper

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      key:
        required: true
        type: string

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Run scraper
      run: |
        docker run -t --rm \
          -e MEILISEARCH_HOST_URL=${{ inputs.host }} \
          -e MEILISEARCH_API_KEY=${{ inputs.key }} \
          -v ${{ github.workspace }}/meilisearch.json:/docs-scraper/meilisearch.json \
          getmeili/docs-scraper:v0.12.4 pipenv run ./docs_scraper meilisearch.json
