name: build

on:
  pull_request:
    paths:
      - "docs/**"
  workflow_call:
    inputs:
      artifactsName:
        required: false
        type: string
        default: Default Name

env:
  NODE_OPTIONS: --max_old_space_size=10000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      # 运行构建脚本
      - name: Build VuePress site
        run: yarn docs:build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: art-${{ inputs.artifactsName }}
          path: docs/.vuepress/dist
          retention-days: 5
