name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/vuepress-build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: master
          # 部署目录为 VuePress 的默认输出目录
          build_dir: .
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
